name: CI

on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/CI.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "index.html"
      - "vite.config.ts"
      - "tsconfig.*"
      - "public/**"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/CI.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "index.html"
      - "vite.config.ts"
      - "tsconfig.*"
      - "public/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: Upload generated output (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist
